import type { Metadata } from "next";
import { Indie_Flower, Josefin_Sans } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import BgLinear from "../frontend/constant/BgLinear";

const fontBody = Josefin_Sans({
  variable: "--font-body",
  subsets: ["latin"],
});

const fontTitle = Indie_Flower({
  variable: "--font-title",
  subsets: ["latin"],
  weight:['400']
});

export const metadata: Metadata = {
  title: "Create test App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${fontTitle.variable} ${fontBody.variable} relative antialiased`}
          >
          <BgLinear />
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
